services:
  blog_backend:
    networks:
      - traefik_blog
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas : 3
    env_file: ".env.prod.backend"
    labels:
      traefik.enable: true
    restart: always

networks:
  traefik_blog:
    external: true

